### ISSUE TITLE
Could not find class motd

### ISSUE THREAD

**Issue by jyr** [arioch/puppet-percona#1]
Hi

I try install percona but return the next errors:

stdin: is not a tty
sh: 
xtrabackup: not found

sh: 
xtrabackup: not found

sh: 
xtrabackup: not found

sh: 
xtrabackup: not found

Could not find class motd for lucid32.lan at /tmp/vagrant-puppet/modules-0/percona/manifests/init.pp:36 on node lucid32.lan

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cd /tmp/vagrant-puppet/manifests && puppet apply --modulepath '/tmp/vagrant-puppet/modules-0' /tmp/vagrant-puppet/manifests/devops.pp

I will need another requirements?

**Comment by arioch** [comment]
Hi,

The motd part is easily fixed by commenting line 36 and 37 in init.pp or by installing R.I. Pienaar's concat motd module. Be sure to enable pluginsync either in your puppet.conf file or at the commandline using puppet agent --test --pluginsync.

The "xtrabackup: not found" will be resolved in the near future. If it bothers you too much just remove the lib directory and you're good to go.

**Comment by kogent** [comment]
It seems like the motd of the day and xtrabackup dependencies should be at least documented in the readme.

**Comment by arioch** [comment]
Alright. Current status: 

Motd has been removed.
And the XtraDB fact has been removed (what was I thinking) in the development branch which will be merged shortly.
