### ISSUE TITLE
mysql root password management

### ISSUE THREAD

**Issue by erik-smit** [arioch/puppet-percona#12]
How is this handled in this module?

If I try to create/set the password with mysql::rights, I have to manually intervene by creating the my.cnf with the password.

**Comment by arioch** [comment]
I'm awaiting a colleague's pull request that should handle this more elegantly.
Should show up pretty soon now.

Thx for your contributions so far! It's highly appreciated.

**Comment by vStone** [comment]
This has been implemented but maybe not in the way you expect. I opted against passing the root password in the commands the module executes because that would expose the root password in the logs and reports. 

You can use percona::mgmt_cnf to create a my.cnf file which will contain credentials for your root (or other admin user). Once the file has been created, you can pass mgmt_cnf to either percona::params (global), percona or percona::rights, percona::database directly. 

You can find more information in the puppetdoc on top of percona::mgmt_cnf.

A short example / copy paste we use.

``` puppet

  $mgmt_cnf = '/etc/.puppet.cnf'

  ## Mysql Management user/password
  $db_pass = hiera('mysql_mgmt_pass',undef)
  $db_user = hiera('mysql_mgmt_user',undef)

  if $db_pass != undef {

    percona::mgmt_cnf {$mgmt_cnf:
      password => $db_pass,
      user     => $db_user,
    } 
    Percona::Mgmt_cnf<| |> -> Percona::Database<| |> -> Percona::Rights<| |>
    class {'percona::params':
        mgmt_cnf => $mgmt_cnf,
    }
  }
  else {
    class {'percona::params': }
  }

  class {'percona': }

  percona::rights {'monitoring@localhost':
    password => 'silly_plaintext',
    priv      => 'select_priv',
  }

```

Note: The way percona::params and percona can be used has changed a little recently. You could declare percona::params globally (not node specific) to specify global options and override them where needed on your node when you use percona.

**Comment by vStone** [comment]
Also - I almost forgot - on debian, you might consider using the debian.cnf that is provided. But I'm unclear on this subject since we use the percona module on centos.

Note2: I am currently trying to add a method to set the root password on installation. Again, this is probably only needed for CentOS who has a root user without password on installation.

**Comment by erik-smit** [comment]
Ahh, ofcourse, on Debian/Ubuntu I could set the root passwords with the debian.cnf, circumventing my current problem with mgmt.cnf.

Looking forward to your next commits.

P.S.: Thank you. The header you use in your .erb is beautiful, you can expect to see it appear in other modules I touch. :)

**Comment by arioch** [comment]
Merge is done so I think it's safe to close this one.

**Comment by erik-smit** [comment]
If you don't hear back from me, it's working for me. :)

Thanks.
